db:
  mongo:
    uri: 'mongodb://127.0.0.1:27017/sn-librarian'
connection:
  init-host:
    - '20.48.92.124'
    - 'sym-test-01.opening-line.jp'
    - 'mikun-testnet.tk'
    - '001-sai-dual.symboltest.net'
  timeout: 5000
  request-count: 100
  request-chunk: 10
